// <auto-generated />
namespace _2BuzzHub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class NewProj : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewProj));
        
        string IMigrationMetadata.Id
        {
            get { return "201503211547575_NewProj"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
